.github/workflows/helm-release.yml, README.md, charts/open-webui/.helmignore, charts/open-webui/Chart.yaml, charts/open-webui/templates/_helpers.tpl, charts/open-webui/templates/ollama-service.yaml, charts/open-webui/templates/ollama-statefulset.yaml, charts/open-webui/templates/webui-deployment.yaml, charts/open-webui/templates/webui-ingress.yaml, charts/open-webui/templates/webui-pvc.yaml, charts/open-webui/templates/webui-service.yaml, charts/open-webui/values-minikube.yaml, charts/open-webui/values.yaml
This PR contains the already existing Helm chart for Open WebUI, as well as the Github workflow file that's needed to release the Helm chart when changes are merged into `main`. The workflow can be seen running successfully on my fork here: https://github.com/0xThresh/helm-charts/actions/runs/8971452219/job/24637219406
You can also see that the Helm chart is available with Helm CLI if you run the commands below:
```
helm repo add 0xthresh-owui https://0xthresh.github.io/helm-charts
helm search repo 0xthresh-owui
```
In order to finish the setup for this workflow to run successfully on this repo, Github Pages must be enabled by a repo contributor. This can be done with the following steps:
1. Create a `gh-pages` branch from `main`.
2. On the `helm-charts` repo, navigate to Settings > …
=> Initial commit with existing chart and new Helm release workflow

charts/open-webui/templates/ollama-service.yaml, charts/open-webui/values.yaml
This commit adds the ability to configure labels for the ollama service in the values.yaml file. Users can now specify custom labels for the ollama service, providing greater flexibility in managing its configuration.
=> feat: add feature to configure ollama service labels via values

charts/open-webui/Chart.yaml, charts/open-webui/README.md
This PR will bump version to 2.0.2 in order to build the chart with the latest commits from #13, which have been merged.
Also, this will update the chart `README.md` using `helm-docs`
=> release: 2.0.2 helm-docs update, bumping version to include latest commits

charts/open-webui/Chart.yaml, charts/open-webui/templates/workload-manager.yaml
This will help with deployment on multi nodes kubernetes cluster with the persistence enabled. That should fix issue #34.
I have tested that the `helm template` command works properly with and without the option:
```shell
helm template --set ollama.enabled=false --set pipelines.enabled=false --set persistence.enabled=false ./charts/open-webui
```
```shell
helm template --set ollama.enabled=false --set pipelines.enabled=false --set persistence.enabled=true ./charts/open-webui
```
I have also deployed the chart on a local minikube to confirm that the open webui container starts properly, and that switching from `persistence` enabled to disabled works.
=> fix: use StatefulSet instead of Deployment if persistence is enabled

charts/open-webui/Chart.yaml, charts/open-webui/README.md, charts/open-webui/templates/service.yaml
Adds two optional fields to the openwebui `service.yaml` template file:
- `clusterIP`: Only valid if service `type: ClusterIP` and defines a static IP address for the service
- `loadBalancerIP`: Only valid if service `type: LoadBalancer` and defines a static IP address for the service
=> feat: Allow optional clusterIP and loadBalancerIP fields on the openwebui service template

charts/open-webui/Chart.yaml, charts/open-webui/templates/workload-manager.yaml
Misconfiguration fix from last PR: https://github.com/open-webui/helm-charts/pull/36#issuecomment-2184996280
This adds `serviceName` configuration in `spec` part of `StatefulSet`, as explained in the documentation: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id
=> fix: set serviceName in StatefulSet spec

.github/workflows/helm-release.yml
Closes #50 
I removed the `azure/setup-helm@v4` action since helm already comes pre-installed on the latest GitHub-hosted runners.
🤞 this works on the first try.
=> Push the helm charts to ghcr.io as an OCI artifact

charts/open-webui/Chart.yaml, charts/open-webui/README.md, charts/open-webui/templates/workload-manager.yaml, charts/open-webui/values.yaml
Allow for `topologySpreadConstraints`.
=> feat: Add topologySpreadConstraints to workload-manager.yaml template

charts/open-webui/Chart.yaml, charts/open-webui/README.md, charts/open-webui/templates/service.yaml
Based on Kubernetes service type [doc](https://github.com/open-webui/helm-charts/commit/d7a271013f863e878672160a8c240d12209f5618), the type of `LoadBalancer` is case sensitive.
Should be `LoadBalancer` instead of `loadBalancer`, thanks.
=> Fix condition case on `loadBalancerIP`

charts/open-webui/Chart.yaml
Skipped v0.3.20 due to an issue with the Docker image not spinning up.
=> Update to v0.3.21

charts/open-webui/Chart.yaml, charts/open-webui/README.md, charts/open-webui/templates/workload-manager.yaml
- TL;DR:
Fix showing Ollama URL in UI 
- Problem:
When ollama.enabled=False, OpenWebUI still showing empty ollama URL.
- Solution proposed in this PR:
For fix ollama in OpenWebUI need to set  ENABLE_OLLAMA_API to false and check make OLLAMA_BASE_URLS optional.
Checks:
=> FIX: ollama url and env vars when ollama.enabled=False

charts/open-webui/Chart.yaml, charts/open-webui/README.md, charts/open-webui/templates/workload-manager.yaml, charts/open-webui/values.yaml
This PRs adds a new parameter `subPath` to `values.yaml` which allows to use a sub folder within an existing volume claim. This is useful when one PVC is used for more applications.
Fixes #99.
=> Support subPath for persistent volumes

charts/open-webui/templates/ingress.yaml, charts/open-webui/values.yaml
This allows others to provide multiple ingress hosts. That's nice for CNAMEs and similar approaches.
This change is not a breaking change and not setting the `additionalHosts` field will have no effect.
Here is an example output:
```yaml
ingress:
enabled: true
class: ""
annotations: {}
host: "chat.k8s.example.com"
additionalHosts:
- "gpt.example.com"
- "chat.example.com"
tls: true
existingSecret: ""
```
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: open-webui
labels:
helm.sh/chart: open-webui-4.0.0
app.kubernetes.io/version: "0.4.0"
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/instance: test
app.kubernetes.io/component: open-webui
spec:
tls:
- hosts:
- "chat.k8s.example.com"
- "gpt.example.com"
- "chat.example.com"
secretName: test-tls
rules:
- host: …
```
=> feat: allow additionalHosts for ingress

.github/workflows/helm-release.yml, charts/open-webui/Chart.yaml
Also removes the semantic release job for now, which is not bumping major versions as expected.
=> feat: Release OWUI v0.4.2

.github/workflows/helm-release.yml, .github/workflows/helm-test-open-webui.yml, .github/workflows/helm-test-pipelines.yml, charts/open-webui/templates/service-account.yaml
This introduces automated CI checks so checking PRs becomes easier on the maintainers.
It does a helm linting check & tries to `kubectl apply` the created objects. If the kubernetes API returns a non-zero exit code, the pipeline will break and we know there is some issue with the provided templates (which then can be seen in the CI logs).
Other than that, I also fixed the broken ServiceAccount as `automountServiceAccountToken` is not part of `metadata`.
=> Fix broken ServiceAccount & introduce automated testing via CI

charts/pipelines/templates/deployment.yaml, charts/pipelines/templates/service-account.yaml, charts/pipelines/values.yaml
Allow us to set service accounts on pipelines as well.
Same as https://github.com/open-webui/helm-charts/pull/110
=> Enable service accounts for pipelines chart

charts/pipelines/templates/deployment.yaml
I might not fully understand, but currently the pipelines are not persisted between restarts because they are stored in `/app/piplines` which is not the current persistent volume. That one is `/app/backend/data`.
`/app/backend/data` is mentioned in [the Openweb-ui readme](https://github.com/open-webui/open-webui/blob/0a26c41c7b58300f37348ba580a4f0d682ca5fbd/README.md#L90) but I see no mention of it in the pipelines repo.
=> Fix Pipelines persistance

.gitignore, charts/pipelines/Chart.yaml, charts/pipelines/templates/_helpers.tpl, charts/pipelines/templates/deployment.yaml, charts/pipelines/templates/pvc.yaml, charts/pipelines/templates/service-account.yaml, charts/pipelines/templates/service.yaml, charts/pipelines/values.yaml
The rationale behind this PR is that there are cases where it becomes quite complicated to deploy the application unless the namespace is explicitly provided — for example, when managing the application using a GitOps approach.
=> Add namespace explicitly to pipelines

.gitignore, charts/open-webui/Chart.yaml, charts/open-webui/README.md, charts/open-webui/templates/_helpers.tpl, charts/open-webui/templates/ingress.yaml, charts/open-webui/templates/pvc.yaml, charts/open-webui/templates/service-account.yaml, charts/open-webui/templates/service.yaml, charts/open-webui/templates/workload-manager.yaml, charts/open-webui/values.yaml
The rationale behind this PR is that there are cases where it becomes quite complicated to deploy the application unless the namespace is explicitly provided — for example, when managing the application using a GitOps approach.
This PR depends on:
- https://github.com/open-webui/helm-charts/pull/121
- https://github.com/apache/tika-helm/pull/22
- https://github.com/otwld/ollama-helm/pull/124
=> Add namespace explicitly for OpenWebUI Chart

charts/open-webui/Chart.yaml, charts/open-webui/README.md, charts/open-webui/templates/workload-manager.yaml, charts/open-webui/values.yaml
To add update strategy, choose **key name 'strategy'** for **'Deployment/spec.strategy'** and **'StatefulSet/spec.updateStrategy'.** Update samver from 4.0.6 to 4.1.0 with minor spec changes
=> Add updateStrategy for workload manager

charts/open-webui/Chart.yaml, charts/open-webui/README.md, charts/open-webui/templates/workload-manager.yaml, charts/open-webui/values.yaml
Hello, folks. I need to set probes to remove 5xx errors when pods restarted. Please review this. Any feedback would be welcome.
- add `livenessProbe`, `readinessProbe`, `startupProbe` for main container
- add values with commented example values
- add key rows in table of readme
- bump the chart version from `5.0.0` to `5.1.0`
=> Add 3 probes to the main container of workload-manager

.github/workflows/helm-test-pipelines.yml, charts/pipelines/README.md
Hello, folks again. To resolve #133, I change CI files remove the ambiguity between `default` and `test-namespace` (very similar to #125). Proposed changes are followings:
- Create the `test-namespace` namespace.
- Deploy the application in the `test-namespace` namespace instead of the `default` namespace.
- Use `kubectl wait` to ensure `pod/pipelines-##########-#####` is ready before proceeding.
I tested proposed workflow in forked repository. Please check my commits. thx
---
This pull request includes a change to the Helm test pipelines workflow to improve the verification process by adding a namespace creation step and ensuring the pipeline pod is ready before proceeding.
Key changes:
* `.github/workflows/helm-test-pipelines.yml`: 
- Added a command to create a new namespace …
=> Fix 'Pipelines' CI to verify chart installing on test-namespace

.github/workflows/helm-release.yml
Hello, folks. I'd like to suggest disabling chart releases for forked repositories by default.
After forking this repository and enabling Actions, I noticed that the `main` branch's workflow attempted to release charts using unconfigured or void variables, causing the pipeline to fail. This behavior seems common across other repositories with similar setups.
The proposed change is simple: it adds a repository slug check to ensure the workflow only proceeds in the original repository unless explicitly configured otherwise. This helps prevent unnecessary actions and failures in forked repositories. If someone wants to release forked chart, they can comment the `if: ...` line.
But it’s a simple but significant change, so rejecting this is totally okay. Please check it, and any feedback would …
=> Fix 'helm-release' CI to disabling chart release for forked repos

charts/open-webui/Chart.yaml, charts/open-webui/templates/NOTES.txt
To resolve #66, I made pilot helm `NOTES.txt` for open-webui chart (as Helper Message).
This is an example command
```sh
helm upgrade --install --cleanup-on-fail \
-n owui-ingress --create-namespace \
--set ingress.enabled=true \
--set ingress.class=nginx \
--set ingress.host=owui.example.com \
--set ingress.tls=true \
--set ingress.existingSecret=owui-tls \
owui-ingress .
```
And this is corresponding note (helper message)
```sh
🎉 Welcome to Open WebUI!!
___                    __        __   _     _   _ ___ 
/ _ \ _ __   ___ _ __  \ \      / /__| |__ | | | |_ _|
| | | | '_ \ / _ \ '_ \  \ \ /\ / / _ \ '_ \| | | || | 
| |_| | |_) |  __/ | | |  \ V  V /  __/ |_) | |_| || | 
\___/| .__/ \___|_| |_|   \_/\_/ \___|_.__/ \___/|___|
|_|                                               
v0.5.4 - …
```
=> Add helm notes (Helper Message)

charts/open-webui/Chart.yaml, charts/open-webui/README.md, charts/open-webui/templates/extra-resources.yaml, charts/open-webui/values.yaml, charts/pipelines/Chart.yaml, charts/pipelines/README.md, charts/pipelines/templates/extra-resources.yaml, charts/pipelines/values.yaml
Hello, folks. I suggest applying values for `extraResources` in the open-webui and pipelines charts. Adding this will allow us to include extra resources such as `ConfigMaps` and `SealedSecrets` in the cluster.
- We can deploy resources together for open-webui without extra deployment.
- Add static configuration from users
- Add synced configuration from other k8s operators
- Add secrets for secure GitOps
**Default**
No resources added from `extraResources`
values.yaml:
```yaml
extraResources:
[]
```
**Deploy ConfigMap and SealedSecret**
- Static resources are added to the cluster.
- Especially useful for synced/encrypted resources for other operators
- example 1: from [emberstack/kubernetes-reflector](https://github.com/emberstack/kubernetes-reflector)
- example 2: from …
=> Add extra resources

charts/open-webui/templates/managed-cert.yaml, charts/open-webui/values-gke-min.yaml, charts/open-webui/values.yaml
This pull request introduces small enhancement to the Open WebUI Helm chart, including the addition of managed certificate support and various ingress configuration options needed for https for improved deployment, while minimizing changes in the default values.yaml.
Key changes include:
* Added a `ManagedCertificate` resource in `managed-cert.yaml` to enable automatic certificate management for specified domains.
* Added `values-gke-min.yaml` to include working gke environment for "minimal" set up - only the main `open-webui `stateful set with no `Ollama`, `Pipelines`, `Tika`, `Redis`, and `WebSocket` support. This setup works with openai and it good as a starting point for deployment in GKE for a new comer. This meant to help users to overcome the issues I faced as new comer to add …
=> Add managed certificate support and update ingress configuration for GKE

charts/open-webui/Chart.yaml, charts/open-webui/README.md
Hello, guys! by https://github.com/open-webui/open-webui/releases/tag/v0.5.11, we need to bump app and chart version.
please take a look
**chore: update open-webui to v0.5.11**
- update open-webui
- app: from v0.5.10 to v0.5.11
- chart: from 5.10.0 to 5.11.0
- no dependency update (not founded from each remotes)
=> Update open-webui to v0.5.11

charts/open-webui/Chart.yaml, charts/open-webui/README.md
Hello, guys!
by https://github.com/open-webui/open-webui/releases/tag/v0.5.13
we need to bump app and chart version.
and... v0.5.14 was released for bugfix in moment. I will follow up for the latest release
**chore: update open-webui to v0.5.13 (chart 5.14.0)**
- update open-webui
- app: from v0.5.12 to v0.5.13
- chart: from 5.13.0 to 5.14.0
- no dependency update
=> Update open-webui to v0.5.13

charts/open-webui/Chart.yaml, charts/open-webui/README.md, charts/open-webui/templates/websocket-redis.yaml, charts/open-webui/values.yaml, charts/pipelines/README.md
This PR introduces new enhancements to the Redis Deployment template within the Helm chart, enabling greater flexibility and configurability. 
Adds support for the following properties:
- **affinity** : Adds the capability to set affinity rules, which can be used to influence the scheduling of Pods on nodes based on certain criteria.
- **tolerations** : Enables setting tolerations, allowing Pods to be scheduled on nodes with matching taints.
These additions are optional and can be specified in the Helm chart values under affinity, and tolerations. This enhancement aims to provide users with more configurability and control over how their Kubernetes Jobs are executed in diverse environments.
=> feat(open-webui): enhance redis deployment with additional configurable properties

charts/pipelines/Chart.yaml, charts/pipelines/README.md, charts/pipelines/templates/deployment.yaml, charts/pipelines/values.yaml
Hello, guys. I suggest a new feature for the pipelines chart. Any question and contribution are welcome 🤗
- To resolve #179
- **feat(pipelines): add `strategy` for updating deployment**
- bump the pipelines chart from 0.2.0 to 0.3.0
```sh
helm template pipelines ./charts/pipelines \
--namespace test-namespace \
--set "strategy.type=RollingUpdate" \
--set "strategy.rollingUpdate.maxSurge=0" \
--set "strategy.rollingUpdate.maxUnavailable=1" \
> owui-pipelines-test.yaml
kubectl create ns test-namespace
kubectl apply -f owui-pipelines-test.yaml
kubectl describe -n test-namespace deploy pipelines | grep "RollingUpdateStrategy"
```
**Run Command**
**Deployment Description (YAML)**
=> feat: [pipelines] add strategy

charts/open-webui/Chart.yaml, charts/open-webui/README.md
Hello, guys
- By https://github.com/open-webui/open-webui/releases/tag/v0.5.15, we need to bump the open-webui chart
**chore: update open-webui to v0.5.15 (chart 5.17.0)**
- update open-webui
- app: from v0.5.14 to v0.5.15
- chart: from 5.16.1 to 5.17.0
- no dependency update
=> Update open-webui to v0.5.15 (chart 5.17.0)

.github/workflows/helm-release.yml
- To resolve #195
- I forgot add milvus repository for [the release workflow](https://github.com/open-webui/helm-charts/actions/runs/13755276088)
- Fix release workflow for **`open-webui-5.21.0`**
Please check it!
=> fix(ci/release): Fix helm dependency for milvus

charts/open-webui/templates/websocket-redis.yaml
I made a mistake when opening the first PR including `websocket.redis.pods.annotations`.
The correct nindent is 8 and I sent 4.
**Before this PR:**
**After this PR:**
=> fix: redis pod annotation nindent 4 to 8

charts/open-webui/Chart.lock
To add support gemma3 properly, please update ollama.
=> Update ollama chart to 1.11.0(ollama 0.6.2)

charts/open-webui/Chart.yaml, charts/open-webui/README.md, charts/open-webui/templates/workload-manager.yaml, charts/open-webui/values.yaml
Gets inline with ollama deployment allowing open-webui deployment to define a runtimeClassName.
Its required if your clusters/node default runtime is different than the one required for nvidia container runtime for. ex. Requires you to set runtimeClassName to "nvidia".
This opens the possiblity to use "-cuda" image with "USE_CUDA_DOCKER=true" allowing Whipser using CUDA.
Merge after: https://github.com/open-webui/helm-charts/pull/208 (because of version number)
=> feat: Added runtimeClassName to open-webui deployment.

.github/workflows/helm-release.yml
Hello! The release for `open-webui-6.5.0` was failed
- This PR fixes the failing pipeline [#14822192905](https://github.com/open-webui/helm-charts/actions/runs/14822192905) triggered by #223
- To resolve the issue, we include the milvus chart in `.github/workflows/helm-release.yml`
Take a look please!
=> fix(ci): Add milvus repo on `helm-release`

charts/open-webui/values-rag-milvus.yaml
To resolve #228,
- This PR will triggered the release pipeline for open-webui-6.5.0
- We include an example values for milvus installation in `charts/open-webui/values-rag-milvus.yaml`
I checked that I can make the knowledge base with the proposed value
- commands:
```sh
helm upgrade --install \
-n owui-milvus --create-namespace \
-f ./charts/open-webui/values-rag-milvus.yaml \
open-webui ./charts/open-webui
```
- result screenshot:
I think this PR can complete the release ☺️
=> feat: Add an example values for RAG and Milvus (triggering open-webui-6.5.0)

charts/open-webui/Chart.yaml, charts/open-webui/README.md, charts/open-webui/templates/_helpers.tpl, charts/open-webui/templates/workload-manager.yaml, charts/open-webui/values.yaml
Hi,
This PR extends the Open WebUI Helm chart to allow the SSO ClientSecret to be defined either directly in the `values.yaml` file or via a Kubernetes Secret for all supported providers.
Additionally, I’ve added validation logic in the helpers to ensure that when an SSO provider is enabled, either the `clientSecret` or the `clientExistingSecret` variable must be provided. If both are defined, the `clientSecret` will be ignored in favor of the `clientExistingSecret`.
The changes were tested locally using helm template, and the rendering works as expected.
For a  given secret for Microsoft SSO,
```console
kubectl create secret generic test --from-literal=mykey=REDACTED
```
`values-test.yaml` is,
```yaml
ollama:
enabled: false
pipelines:
enabled: false
extraEnvVars: []
tika:
enabled: false …
```
=> feat(open-webui): Make it possible to define SSO OAuth secrets from Kubernetes Secrets

charts/open-webui/Chart.yaml, charts/open-webui/README.md, charts/open-webui/templates/workload-manager.yaml, charts/open-webui/values.yaml
Hi,
This PR extends the Open WebUI Helm chart to allow the Storage Key to be defined either directly in the values.yaml file or via a Kubernetes Secret. I took the opportunity to define new README.md sections called  "Azure Storage configuration", "Google Cloud Storage configuration", and "Amazon S3 Storage configuration" respectively.
The changes were tested locally using helm template, and the rendering works as expected.
Given a k8s secret like,
```console
kubectl create secret generic azure-storage-account --from-literal=azure-account-key=REDACTED
```
And a values-test.yaml file,
```yaml
ollama:
enabled: false
pipelines:
enabled: false
extraEnvVars: []
tika:
enabled: false
ollamaUrls: []
ollamaUrlsFromExtraEnv: false
websocket:
enabled: true
manager: redis
redis:
enabled: false …
```
=> feat(open-webui): Make it possible to configure Storage credentials via k8s secrets

charts/open-webui/Chart.yaml, charts/open-webui/README.md, charts/open-webui/templates/_helpers.tpl, charts/open-webui/templates/workload-manager.yaml, charts/open-webui/values.yaml
Hi,
This PR add the [Application logging configuration](https://docs.openwebui.com/getting-started/advanced-topics/logging#%EF%B8%8F-application-serverbackend-logging-python) to the Open WebUI Helm chart. 
The changes were tested locally using helm template, and the rendering works as expected.
This is a simple `values.yaml` file for testing,
```yaml
ollama:
enabled: false
pipelines:
enabled: false
extraEnvVars: []
tika:
enabled: false
ollamaUrls: []
ollamaUrlsFromExtraEnv: false
websocket:
enabled: true
manager: redis
redis:
enabled: false
redis-cluster:
enabled: true
fullnameOverride: open-webui-redis
auth:
enabled: false
replica:
replicaCount: 3
replicaCount: 2
serviceAccount:
enable: true
ingress:
enabled: true
class: "external"
annotations:
cert-manager.io/cluster-issuer: letsencrypt …
```
=> feat(open-webui): Add application logging configuration

charts/open-webui/templates/websocket-redis.yaml, charts/open-webui/values.yaml
This PR adds nodeSelector support to the websocket Redis deployment in the Helm chart. It allows users to specify which nodes the Redis pods for websockets should be scheduled on, providing better control over pod placement in Kubernetes clusters.
=> Add nodeSelector support to websocket Redis deployment

charts/open-webui/README.md, charts/open-webui/templates/workload-manager.yaml, charts/open-webui/values.yaml
Allows users to define a list of environment variables that are common across environments, avoiding repetition in `extraEnvVars`.
=> feat(open-webui): add support for commonEnvVars to inject shared environments variables

charts/open-webui/Chart.yaml, charts/open-webui/README.md, charts/open-webui/templates/ingress.yaml, charts/open-webui/values.yaml
This adds support for `ingress.extraLabels` in the Helm chart, allowing users to define additional metadata labels for the Ingress resource. Includes documentation comments in values.yaml to guide usage.
=> feat(open-webui): support extraLabels for custom metadata in Ingress

charts/open-webui/Chart.lock, charts/open-webui/Chart.yaml, charts/open-webui/README.md
chore: update Chart.lock
- Updated subchart versions (pipelines, redis, postgresql)
=> chore: bump chart version to 6.13.0 and update subchart dependencies

charts/open-webui/Chart.yaml, charts/open-webui/README.md, charts/open-webui/templates/websocket-redis.yaml, charts/open-webui/values.yaml
Allows users to define labels in the pod-level in websocket redis.
=> feat(open-webui): add pod labels to websocket-redis

charts/open-webui/Chart.lock, charts/open-webui/Chart.yaml, charts/open-webui/README.md
- upgrade open-webui to v0.6.9 (chart v6.15.0)
- upgrade subcharts (redis v21.1.3 - postgresql v16.7.4)
=> chore(open-webui): upgrade open-webui to v0.6.9 (chart v6.15.0)

charts/open-webui/Chart.lock, charts/open-webui/Chart.yaml, charts/open-webui/README.md
- upgrade open-webui to [v0.6.10](https://github.com/open-webui/open-webui/releases/tag/v0.6.10) (chart v6.16.0)
- upgrade subcharts (ollama chart [v1.17.0](https://github.com/otwld/ollama-helm/releases/tag/ollama-1.17.0))
=> chore(open-webui): upgrade open-webui to v0.6.10 (chart v6.16.0)

charts/open-webui/Chart.lock, charts/open-webui/Chart.yaml, charts/open-webui/README.md
- upgrade open-webui to [v0.6.10](https://github.com/open-webui/open-webui/releases/tag/v0.6.11) (chart v6.17.0)
- ollama chart [v1.18.0](https://github.com/otwld/ollama-helm/releases/tag/ollama-1.18.0)
- pipelines chart [v0.7.0](https://github.com/open-webui/helm-charts/releases/tag/pipelines-0.7.0)
- redis chart [v21.1.8](https://github.com/bitnami/charts/blob/main/bitnami/redis/CHANGELOG.md#2118-2025-05-27)
- postgresql chart [v21.1.8](https://github.com/bitnami/charts/blob/main/bitnami/postgresql/CHANGELOG.md#1675-2025-05-27)
=> chore(open-webui): upgrade open-webui to v0.6.11 (chart v6.17.0)

charts/open-webui/templates/_helpers.tpl, charts/open-webui/templates/workload-manager.yaml
When ingress is enabled it adds the WEBUI_URL variable with the value correctly rendered based on the ingress configuration.
This fixes the problem of being redirecting to "http://localhost:3000" once authentication process is completed, when both ingress and sso are enabled.
=> fix(open-webui): add WEBUI_URL env var when ingress is enabled

charts/open-webui/templates/_helpers.tpl, charts/open-webui/templates/workload-manager.yaml
We use a redirect in our setup, which means the ingress host is different then the WEBUI_URL. 
This change allows to set the WEBUI_URL either manually via extraenv or via ingress.host
=> Allow setting WEBUI_URL manually

charts/open-webui/Chart.lock, charts/open-webui/Chart.yaml, charts/open-webui/README.md
- upgrade open-webui to [v0.6.14](https://github.com/open-webui/open-webui/releases/tag/v0.6.14) (chart v6.20.0)
- redis [v21.2.2](https://github.com/bitnami/charts/blob/main/bitnami/redis/CHANGELOG.md#2122-2025-06-10)
- postgresql [v16.7.10](https://github.com/bitnami/charts/blob/main/bitnami/postgresql/CHANGELOG.md#16710-2025-06-06)
=> chore(open-webui): upgrade open-webui to v0.6.14 (chart v6.20.0)

charts/open-webui/Chart.lock, charts/open-webui/Chart.yaml, charts/open-webui/README.md
- upgrade open-webui to [v0.6.18](https://github.com/open-webui/open-webui/releases/tag/v0.6.18) (chart v6.26.0)
- ollama [v1.24.0](https://github.com/otwld/ollama-helm/releases/tag/ollama-1.24.0)
- redis [v21.2.12](https://github.com/bitnami/charts/blob/main/bitnami/redis/CHANGELOG.md#21212-2025-07-16)
- postgresql [v16.7.20](https://github.com/bitnami/charts/blob/main/bitnami/postgresql/CHANGELOG.md#16720-2025-07-18)
---
*This PR should be merged after #264*
=> chore(open-webui): upgrade open-webui to v0.6.18 (chart v6.26.0)

charts/open-webui/Chart.yaml, charts/open-webui/README.md, charts/open-webui/templates/workload-manager.yaml, charts/open-webui/values.yaml
In Version 7.0.0 `databaseUrl` has been removed, but this value is not part of bitnamis helm chart and should be available for external Postgres support.
=> Add databaseUrl back again

charts/open-webui/Chart.yaml, charts/open-webui/README.md
- upgrade open-webui to [v0.6.23](https://github.com/open-webui/open-webui/releases/tag/v0.6.23) (chart v7.4.0)
---
I made 2 PR related to the 2 new versions of Open Webui:
- this one (#285) to upgrade Open Webui to `v0.6.23`.
- another one (#286) to upgrade Open Webui to `v0.6.24` (and subcharts as well). This one is already based on the first one to simplify the rebase process.
=> chore(open-webui): upgrade open-webui to v0.6.23 (chart v7.4.0)

charts/open-webui/Chart.yaml, charts/open-webui/README.md, charts/open-webui/templates/websocket-redis.yaml, charts/open-webui/values.yaml
securityContext could only be set on pod level, not container level. So a read only root filesystem could not be
set.
In addition, if readOnlyRootFilesystem is set, mount an emptyDir at /data for redis to have write access.
=> feat!: allow redis security context on container level

charts/open-webui/Chart.yaml, charts/open-webui/README.md, charts/open-webui/templates/_helpers.tpl, charts/pipelines/Chart.yaml, charts/pipelines/README.md, charts/pipelines/templates/_helpers.tpl
This label is suggested by Helm best practices and have general use for eg. monitoring etc, where the standard set of labels help identify the application.
https://helm.sh/docs/chart_best_practices/labels/
=> feat: add app.kubernetes.io/name labels

charts/open-webui/Chart.lock, charts/open-webui/Chart.yaml, charts/open-webui/README.md
- upgrade open-webui to [v0.6.30](https://github.com/open-webui/open-webui/releases/tag/v0.6.30) (chart v8.6.0)
- ollama [v1.29.0](https://github.com/otwld/ollama-helm/releases/tag/ollama-1.29.0)
- pipelines [v0.9.0](https://github.com/open-webui/helm-charts/releases/tag/pipelines-0.9.0)
---
*This PR should be merged after #298*
=> chore(open-webui): upgrade open-webui to v0.6.30 (chart v8.6.0)

charts/open-webui/Chart.yaml, charts/open-webui/README.md, charts/open-webui/templates/_helpers.tpl, charts/open-webui/templates/workload-manager.yaml, charts/open-webui/values.yaml
Support slim version by allowing use of image.useSlim in the values.yaml
Image tag resolution uses the helper implemented earlier:
- explicit .Values.image.tag if set
- else .Chart.AppVersion-slim when image.useSlim: true
- else .Chart.AppVersion
Related issue: https://github.com/open-webui/helm-charts/issues/291
=> Support slim image

charts/open-webui/Chart.lock, charts/open-webui/Chart.yaml, charts/open-webui/README.md
- upgrade open-webui to [v0.6.33](https://github.com/open-webui/open-webui/releases/tag/v0.6.33) (chart v8.10.0)
- ollama [v1.31.0](https://github.com/otwld/ollama-helm/releases/tag/ollama-1.31.0)
=> chore(open-webui): upgrade open-webui to v0.6.33 (chart v8.10.0)
