open-webui/helm-charts

- charts/open-webui/Chart.yaml
- charts/open-webui/templates/deployment.yaml
- charts/open-webui/values.yaml
- **render envVars as yaml (allow valueFrom)**
- **add env var example**
relates to #14 
allows use of secrets and config maps as sources for env var values (e.g. OPENAI_API_KEY as a secret)
> render env vars as yaml

- charts/open-webui/Chart.yaml
- charts/open-webui/README.md
- charts/open-webui/templates/workload-manager.yaml
- charts/open-webui/values.yaml
Adds pod- and container-level security context settings to the values.yaml
> feat: configure pod and container security context settings

- charts/open-webui/Chart.yaml
- charts/open-webui/README.md
- charts/open-webui/templates/workload-manager.yaml
- charts/open-webui/values.yaml
- charts/pipelines/Chart.yaml
- charts/pipelines/README.md
- charts/pipelines/templates/deployment.yaml
- charts/pipelines/values.yaml
Closes #59
Adding imagePullSecrets to both the helm charts
@0xThresh, please review and merge if it looks good.
> feat: adding imagepullsecrets to open-webui and pipelines

- charts/open-webui/Chart.yaml
- charts/open-webui/README.md
- charts/open-webui/templates/configmap.yaml
- charts/open-webui/templates/workload-manager.yaml
- charts/open-webui/values.yaml
Closes https://github.com/open-webui/helm-charts/issues/22
> feat: Move env vars from deployment to a configmap for easier management

- charts/open-webui/Chart.yaml
Tested and verified on my cluster.
> Update to v0.3.30

- charts/pipelines/values.yaml
> docs: add how to set custom api key

- charts/open-webui/Chart.yaml
Verified on my production cluster.
> Update to v0.3.35

- charts/open-webui/templates/workload-manager.yaml
- charts/open-webui/values.yaml
- charts/pipelines/templates/deployment.yaml
- charts/pipelines/values.yaml
Added support for optional pod labels
> feat: Support for podLabels

- charts/open-webui/Chart.yaml
- charts/open-webui/values.yaml
Hello, folks. I am writing PR to resolve #158
- Fix commented values with `pull` and `run`
- And I updated chart version by patch: from 5.10.0 to 5.10.1
- see my another opinion about versioning issue #159 
Please check about it. Thank you
> Fix example values for Ollama pull and run

- charts/open-webui/Chart.yaml
- charts/open-webui/README.md
**chore: update open-webui to v0.5.14 (chart 5.15.0)**
- update open-webui
- app: from v0.5.13 to v0.5.14
- chart: from 5.14.0 to 5.15.0
- no dependency update
> Update open-webui to v0.5.14 (chart 5.15.0)

- CONTRIBUTING.md
Add link to helm-docs: https://github.com/norwoodj/helm-docs
> CONTRIBUTING.md: Add link to helm-docs

- charts/open-webui/Chart.lock
- charts/open-webui/Chart.yaml
- charts/open-webui/README.md
- charts/open-webui/templates/workload-manager.yaml
- charts/open-webui/values.yaml
- charts/pipelines/Chart.yaml
- charts/pipelines/README.md
- charts/pipelines/templates/deployment.yaml
- charts/pipelines/values.yaml
This PR adds support for setting hostAliases for both helm charts.
> feat: Add support for hostAliases

- charts/open-webui/templates/websocket-redis.yaml
update open-webui helm chart websocket-redis.yml template
* add option adding image pull secrets for redis image
> image pull secrets for websocket-redis.yml template

- charts/open-webui/README.md
- charts/open-webui/templates/workload-manager.yaml
- charts/open-webui/values.yaml
Use the following value to disable openai api
```yaml
enableOpenaiApi: false
```
instead of
```yaml
extraEnvVars:
- name: "ENABLE_OPENAI_API"
value: "False"
```
> feat: add  option to disable openai api

- charts/open-webui/values.yaml
Just a little typo I stumbled upon.
> docs: Fix typo in URL

- .github/workflows/helm-release.yml
Reverts open-webui/helm-charts#196
> Revert "fix(ci/release): Fix helm dependency for milvus"

- charts/open-webui/Chart.lock
Update Ollama  0.6.3(Chart 1.12.0)
> Update ollama chart to 1.12.0(ollama 0.6.3)

- charts/open-webui/README.md
- charts/open-webui/templates/workload-manager.yaml
- charts/open-webui/values.yaml
> Add support for SSO/OIDC

- charts/open-webui/Chart.yaml
- charts/open-webui/README.md
Update openweb-ui to [v0.6.1](https://github.com/open-webui/open-webui/releases/tag/v0.6.1)
> chore: update openweb-ui to v0.6.1 (chart 6.1.0)

- .github/workflows/helm-test-open-webui.yml
- charts/open-webui/Chart.lock
- charts/open-webui/Chart.yaml
- charts/open-webui/README.md
- charts/open-webui/templates/workload-manager.yaml
- charts/open-webui/values.yaml
- Re-enable Milvus, based on https://github.com/open-webui/helm-charts/pull/203
> feat: re-enable milvus support in open-webui chart

- charts/pipelines/Chart.yaml
- charts/pipelines/README.md
- charts/pipelines/templates/deployment.yaml
- charts/pipelines/values.yaml
Allows users to define a list of environment variables that are common across environments, avoiding repetition in `extraEnvVars`.
> feat(pipelines): add support for commonEnvVars for shared environment variables across environments. 

- charts/open-webui/Chart.yaml
- charts/open-webui/README.md
- charts/open-webui/templates/ingress.yaml
Added the [Helm tpl](https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function) function for input annotations, allowing the annotation value to be dynamically allocated by retrieving it from a value file. A concrete use case is the generation of a whitelist of IP addresses maintained as code.
Values file:
```yaml
whitelist:
- '10.0.0.0/24'
- '172.10.0.0/24'
ingress:
enabled: true
annotations:
nginx.ingress.kubernetes.io/whitelist-source-range: '{{ .Values.whitelist | join "," | default "0.0.0.0/0" }}'
```
Command used to test: 
```sh
helm template open-webui ./charts/open-webui -f ./charts/open-webui/test-values.yaml --debug
```
Output without the change:
```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: open-webui
namespace: …
```
> feat(open-webui): handle usage of tpl function in ingress annotations

- charts/open-webui/Chart.yaml
- charts/open-webui/README.md
- charts/open-webui/templates/workload-manager.yaml
- charts/open-webui/values.yaml
closes https://github.com/open-webui/helm-charts/issues/192
> feat: add support for revisionHistoryLimit and priorityClassName

- .github/workflows/helm-release.yml
- .github/workflows/helm-test-open-webui.yml
- charts/open-webui/Chart.lock
- charts/open-webui/Chart.yaml
- charts/open-webui/README.md
- charts/open-webui/templates/workload-manager.yaml
- charts/open-webui/values-gke-min.yaml
- charts/open-webui/values.yaml
See https://github.com/open-webui/helm-charts/issues/273 for more details. We are planning to complete this PR and testing before the end of July.
> BREAKING CHANGE: Drop support for Bitnami Postgres and Redis charts

- charts/open-webui/Chart.yaml
- charts/open-webui/README.md
- upgrade open-webui to [v0.6.27](https://github.com/open-webui/open-webui/releases/tag/v0.6.27) (chart v8.3.0)
> chore(open-webui): upgrade open-webui to v0.6.27 (chart v8.3.0)

- charts/open-webui/Chart.yaml
- charts/open-webui/README.md
- upgrade open-webui to [v0.6.31](https://github.com/open-webui/open-webui/releases/tag/v0.6.31) (chart v8.7.0)
> chore(open-webui): upgrade open-webui to v0.6.31 (chart v8.7.0)

- charts/open-webui/Chart.yaml
- charts/open-webui/README.md
- upgrade open-webui to [v0.6.32](https://github.com/open-webui/open-webui/releases/tag/v0.6.32) (chart v8.8.0)
> chore(open-webui): upgrade open-webui to v0.6.32 (chart v8.8.0)
